/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.tests;

import junit.textui.TestRunner;

import org.xtext.blogPostDSL.Blog;
import org.xtext.blogPostDSL.BlogPostDSLFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Blog</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class BlogTest extends ItemElementTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(BlogTest.class);
	}

	/**
	 * Constructs a new Blog test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BlogTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Blog test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Blog getFixture() {
		return (Blog)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(BlogPostDSLFactory.eINSTANCE.createBlog());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //BlogTest
