/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.tests;

import junit.framework.Test;
import junit.framework.TestSuite;

import junit.textui.TestRunner;

/**
 * <!-- begin-user-doc -->
 * A test suite for the '<em><b>blogPostDSL</b></em>' package.
 * <!-- end-user-doc -->
 * @generated
 */
public class BlogPostDSLTests extends TestSuite {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(suite());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static Test suite() {
		TestSuite suite = new BlogPostDSLTests("blogPostDSL Tests");
		return suite;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public BlogPostDSLTests(String name) {
		super(name);
	}

} //BlogPostDSLTests
