/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.xtext.blogPostDSL.BlogPostDSLFactory;
import org.xtext.blogPostDSL.ItemElement;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Item Element</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ItemElementTest extends TestCase {

	/**
	 * The fixture for this Item Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ItemElement fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ItemElementTest.class);
	}

	/**
	 * Constructs a new Item Element test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ItemElementTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Item Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(ItemElement fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Item Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ItemElement getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(BlogPostDSLFactory.eINSTANCE.createItemElement());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ItemElementTest
