/**
 * generated by Xtext 2.10.0
 */
package org.xtext.web;

import com.google.inject.Binder;
import com.google.inject.Provider;
import com.google.inject.binder.AnnotatedBindingBuilder;
import com.google.inject.binder.LinkedBindingBuilder;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.formatting2.FormatterPreferenceValuesProvider;
import org.eclipse.xtext.formatting2.FormatterPreferences;
import org.eclipse.xtext.preferences.IPreferenceValuesProvider;
import org.xtext.web.AbstractBlogPostDSLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BlogPostDSLWebModule extends AbstractBlogPostDSLWebModule {
  public void configureIPreferenceValuesProvider(final Binder binder) {
    AnnotatedBindingBuilder<IPreferenceValuesProvider> _bind = binder.<IPreferenceValuesProvider>bind(IPreferenceValuesProvider.class);
    LinkedBindingBuilder<IPreferenceValuesProvider> _annotatedWith = _bind.annotatedWith(FormatterPreferences.class);
    _annotatedWith.to(FormatterPreferenceValuesProvider.class);
  }
  
  public BlogPostDSLWebModule(final Provider<ExecutorService> arg0) {
    super(arg0);
  }
}
