/**
 * generated by Xtext 2.10.0
 */
package org.xtext.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.google.inject.Module;
import com.google.inject.Provider;
import com.google.inject.util.Modules;
import java.util.concurrent.ExecutorService;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.BlogPostDSLRuntimeModule;
import org.xtext.BlogPostDSLStandaloneSetup;
import org.xtext.web.BlogPostDSLWebModule;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BlogPostDSLWebSetup extends BlogPostDSLStandaloneSetup {
  private final Provider<ExecutorService> executorServiceProvider;
  
  @Override
  public Injector createInjector() {
    final BlogPostDSLRuntimeModule runtimeModule = new BlogPostDSLRuntimeModule();
    final BlogPostDSLWebModule webModule = new BlogPostDSLWebModule(this.executorServiceProvider);
    Modules.OverriddenModuleBuilder _override = Modules.override(runtimeModule);
    Module _with = _override.with(webModule);
    return Guice.createInjector(_with);
  }
  
  public BlogPostDSLWebSetup(final Provider<ExecutorService> executorServiceProvider) {
    super();
    this.executorServiceProvider = executorServiceProvider;
  }
}
