/**
 * generated by Xtext 2.10.0
 */
package org.xtext.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.tests.BlogPostDSLInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(BlogPostDSLInjectorProvider.class)
@SuppressWarnings("all")
public class BlogPostDSLParsingTest {
  @Inject
  private /* ParseHelper<Domainmodel> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field BlogPostDSLParsingTest.parseHelper refers to the missing type Domainmodel");
  }
}
