/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Blog</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getBlog()
 * @model
 * @generated
 */
public interface Blog extends ItemElement
{
} // Blog
