/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.blogPostDSL.BlogPostDSLFactory
 * @model kind="package"
 * @generated
 */
public interface BlogPostDSLPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "blogPostDSL";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.xtext.org/BlogPostDSL";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "blogPostDSL";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  BlogPostDSLPackage eINSTANCE = org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl.init();

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.DomainmodelImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getDomainmodel()
	 * @generated
	 */
  int DOMAINMODEL = 0;

  /**
	 * The feature id for the '<em><b>Tag Import</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DOMAINMODEL__TAG_IMPORT = 0;

  /**
	 * The feature id for the '<em><b>Item Element</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DOMAINMODEL__ITEM_ELEMENT = 1;

  /**
	 * The number of structural features of the '<em>Domainmodel</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DOMAINMODEL_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.ItemElementImpl <em>Item Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.ItemElementImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getItemElement()
	 * @generated
	 */
  int ITEM_ELEMENT = 1;

  /**
	 * The feature id for the '<em><b>Declaration</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ITEM_ELEMENT__DECLARATION = 0;

  /**
	 * The number of structural features of the '<em>Item Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ITEM_ELEMENT_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.BlogImpl <em>Blog</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.BlogImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getBlog()
	 * @generated
	 */
  int BLOG = 2;

  /**
	 * The feature id for the '<em><b>Declaration</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int BLOG__DECLARATION = ITEM_ELEMENT__DECLARATION;

  /**
	 * The number of structural features of the '<em>Blog</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int BLOG_FEATURE_COUNT = ITEM_ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.ArticleImpl <em>Article</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.ArticleImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getArticle()
	 * @generated
	 */
  int ARTICLE = 3;

  /**
	 * The feature id for the '<em><b>Declaration</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ARTICLE__DECLARATION = ITEM_ELEMENT__DECLARATION;

  /**
	 * The number of structural features of the '<em>Article</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ARTICLE_FEATURE_COUNT = ITEM_ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.ElementDeclarationImpl <em>Element Declaration</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.ElementDeclarationImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getElementDeclaration()
	 * @generated
	 */
  int ELEMENT_DECLARATION = 4;

  /**
	 * The number of structural features of the '<em>Element Declaration</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ELEMENT_DECLARATION_FEATURE_COUNT = 0;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.TagImportImpl <em>Tag Import</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.TagImportImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTagImport()
	 * @generated
	 */
  int TAG_IMPORT = 5;

  /**
	 * The number of structural features of the '<em>Tag Import</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TAG_IMPORT_FEATURE_COUNT = 0;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.TagImpl <em>Tag</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.TagImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTag()
	 * @generated
	 */
  int TAG = 6;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TAG__NAME = TAG_IMPORT_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>Tag</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TAG_FEATURE_COUNT = TAG_IMPORT_FEATURE_COUNT + 1;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.TitleImpl <em>Title</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.TitleImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTitle()
	 * @generated
	 */
  int TITLE = 7;

  /**
	 * The feature id for the '<em><b>Date</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TITLE__DATE = ELEMENT_DECLARATION_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Tag</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TITLE__TAG = ELEMENT_DECLARATION_FEATURE_COUNT + 1;

  /**
	 * The feature id for the '<em><b>Name</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TITLE__NAME = ELEMENT_DECLARATION_FEATURE_COUNT + 2;

  /**
	 * The number of structural features of the '<em>Title</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TITLE_FEATURE_COUNT = ELEMENT_DECLARATION_FEATURE_COUNT + 3;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.DateImpl <em>Date</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.DateImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getDate()
	 * @generated
	 */
  int DATE = 8;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DATE__NAME = 0;

  /**
	 * The number of structural features of the '<em>Date</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DATE_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.TagsImpl <em>Tags</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.TagsImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTags()
	 * @generated
	 */
  int TAGS = 9;

  /**
	 * The feature id for the '<em><b>Name</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TAGS__NAME = 0;

  /**
	 * The number of structural features of the '<em>Tags</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TAGS_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link org.xtext.blogPostDSL.impl.TitleIDImpl <em>Title ID</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see org.xtext.blogPostDSL.impl.TitleIDImpl
	 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTitleID()
	 * @generated
	 */
  int TITLE_ID = 10;

  /**
	 * The feature id for the '<em><b>Titleid</b></em>' attribute list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TITLE_ID__TITLEID = 0;

  /**
	 * The number of structural features of the '<em>Title ID</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TITLE_ID_FEATURE_COUNT = 1;


  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.Domainmodel <em>Domainmodel</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Domainmodel</em>'.
	 * @see org.xtext.blogPostDSL.Domainmodel
	 * @generated
	 */
  EClass getDomainmodel();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.blogPostDSL.Domainmodel#getTagImport <em>Tag Import</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Tag Import</em>'.
	 * @see org.xtext.blogPostDSL.Domainmodel#getTagImport()
	 * @see #getDomainmodel()
	 * @generated
	 */
  EReference getDomainmodel_TagImport();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.blogPostDSL.Domainmodel#getItemElement <em>Item Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Item Element</em>'.
	 * @see org.xtext.blogPostDSL.Domainmodel#getItemElement()
	 * @see #getDomainmodel()
	 * @generated
	 */
  EReference getDomainmodel_ItemElement();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.ItemElement <em>Item Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Item Element</em>'.
	 * @see org.xtext.blogPostDSL.ItemElement
	 * @generated
	 */
  EClass getItemElement();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.blogPostDSL.ItemElement#getDeclaration <em>Declaration</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Declaration</em>'.
	 * @see org.xtext.blogPostDSL.ItemElement#getDeclaration()
	 * @see #getItemElement()
	 * @generated
	 */
  EReference getItemElement_Declaration();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.Blog <em>Blog</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Blog</em>'.
	 * @see org.xtext.blogPostDSL.Blog
	 * @generated
	 */
  EClass getBlog();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.Article <em>Article</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Article</em>'.
	 * @see org.xtext.blogPostDSL.Article
	 * @generated
	 */
  EClass getArticle();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.ElementDeclaration <em>Element Declaration</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Element Declaration</em>'.
	 * @see org.xtext.blogPostDSL.ElementDeclaration
	 * @generated
	 */
  EClass getElementDeclaration();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.TagImport <em>Tag Import</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Tag Import</em>'.
	 * @see org.xtext.blogPostDSL.TagImport
	 * @generated
	 */
  EClass getTagImport();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.Tag <em>Tag</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Tag</em>'.
	 * @see org.xtext.blogPostDSL.Tag
	 * @generated
	 */
  EClass getTag();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.blogPostDSL.Tag#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.blogPostDSL.Tag#getName()
	 * @see #getTag()
	 * @generated
	 */
  EAttribute getTag_Name();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.Title <em>Title</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Title</em>'.
	 * @see org.xtext.blogPostDSL.Title
	 * @generated
	 */
  EClass getTitle();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.blogPostDSL.Title#getDate <em>Date</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Date</em>'.
	 * @see org.xtext.blogPostDSL.Title#getDate()
	 * @see #getTitle()
	 * @generated
	 */
  EReference getTitle_Date();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.blogPostDSL.Title#getTag <em>Tag</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Tag</em>'.
	 * @see org.xtext.blogPostDSL.Title#getTag()
	 * @see #getTitle()
	 * @generated
	 */
  EReference getTitle_Tag();

  /**
	 * Returns the meta object for the containment reference '{@link org.xtext.blogPostDSL.Title#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Name</em>'.
	 * @see org.xtext.blogPostDSL.Title#getName()
	 * @see #getTitle()
	 * @generated
	 */
  EReference getTitle_Name();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.Date <em>Date</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Date</em>'.
	 * @see org.xtext.blogPostDSL.Date
	 * @generated
	 */
  EClass getDate();

  /**
	 * Returns the meta object for the attribute '{@link org.xtext.blogPostDSL.Date#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see org.xtext.blogPostDSL.Date#getName()
	 * @see #getDate()
	 * @generated
	 */
  EAttribute getDate_Name();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.Tags <em>Tags</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Tags</em>'.
	 * @see org.xtext.blogPostDSL.Tags
	 * @generated
	 */
  EClass getTags();

  /**
	 * Returns the meta object for the reference '{@link org.xtext.blogPostDSL.Tags#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Name</em>'.
	 * @see org.xtext.blogPostDSL.Tags#getName()
	 * @see #getTags()
	 * @generated
	 */
  EReference getTags_Name();

  /**
	 * Returns the meta object for class '{@link org.xtext.blogPostDSL.TitleID <em>Title ID</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Title ID</em>'.
	 * @see org.xtext.blogPostDSL.TitleID
	 * @generated
	 */
  EClass getTitleID();

  /**
	 * Returns the meta object for the attribute list '{@link org.xtext.blogPostDSL.TitleID#getTitleid <em>Titleid</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute list '<em>Titleid</em>'.
	 * @see org.xtext.blogPostDSL.TitleID#getTitleid()
	 * @see #getTitleID()
	 * @generated
	 */
  EAttribute getTitleID_Titleid();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  BlogPostDSLFactory getBlogPostDSLFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.DomainmodelImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getDomainmodel()
		 * @generated
		 */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
		 * The meta object literal for the '<em><b>Tag Import</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference DOMAINMODEL__TAG_IMPORT = eINSTANCE.getDomainmodel_TagImport();

    /**
		 * The meta object literal for the '<em><b>Item Element</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference DOMAINMODEL__ITEM_ELEMENT = eINSTANCE.getDomainmodel_ItemElement();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.ItemElementImpl <em>Item Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.ItemElementImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getItemElement()
		 * @generated
		 */
    EClass ITEM_ELEMENT = eINSTANCE.getItemElement();

    /**
		 * The meta object literal for the '<em><b>Declaration</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ITEM_ELEMENT__DECLARATION = eINSTANCE.getItemElement_Declaration();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.BlogImpl <em>Blog</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.BlogImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getBlog()
		 * @generated
		 */
    EClass BLOG = eINSTANCE.getBlog();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.ArticleImpl <em>Article</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.ArticleImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getArticle()
		 * @generated
		 */
    EClass ARTICLE = eINSTANCE.getArticle();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.ElementDeclarationImpl <em>Element Declaration</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.ElementDeclarationImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getElementDeclaration()
		 * @generated
		 */
    EClass ELEMENT_DECLARATION = eINSTANCE.getElementDeclaration();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.TagImportImpl <em>Tag Import</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.TagImportImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTagImport()
		 * @generated
		 */
    EClass TAG_IMPORT = eINSTANCE.getTagImport();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.TagImpl <em>Tag</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.TagImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTag()
		 * @generated
		 */
    EClass TAG = eINSTANCE.getTag();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute TAG__NAME = eINSTANCE.getTag_Name();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.TitleImpl <em>Title</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.TitleImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTitle()
		 * @generated
		 */
    EClass TITLE = eINSTANCE.getTitle();

    /**
		 * The meta object literal for the '<em><b>Date</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference TITLE__DATE = eINSTANCE.getTitle_Date();

    /**
		 * The meta object literal for the '<em><b>Tag</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference TITLE__TAG = eINSTANCE.getTitle_Tag();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference TITLE__NAME = eINSTANCE.getTitle_Name();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.DateImpl <em>Date</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.DateImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getDate()
		 * @generated
		 */
    EClass DATE = eINSTANCE.getDate();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute DATE__NAME = eINSTANCE.getDate_Name();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.TagsImpl <em>Tags</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.TagsImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTags()
		 * @generated
		 */
    EClass TAGS = eINSTANCE.getTags();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference TAGS__NAME = eINSTANCE.getTags_Name();

    /**
		 * The meta object literal for the '{@link org.xtext.blogPostDSL.impl.TitleIDImpl <em>Title ID</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see org.xtext.blogPostDSL.impl.TitleIDImpl
		 * @see org.xtext.blogPostDSL.impl.BlogPostDSLPackageImpl#getTitleID()
		 * @generated
		 */
    EClass TITLE_ID = eINSTANCE.getTitleID();

    /**
		 * The meta object literal for the '<em><b>Titleid</b></em>' attribute list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute TITLE_ID__TITLEID = eINSTANCE.getTitleID_Titleid();

  }

} //BlogPostDSLPackage
