/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getElementDeclaration()
 * @model
 * @generated
 */
public interface ElementDeclaration extends EObject
{
} // ElementDeclaration
