/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Item Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.blogPostDSL.ItemElement#getDeclaration <em>Declaration</em>}</li>
 * </ul>
 *
 * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getItemElement()
 * @model
 * @generated
 */
public interface ItemElement extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration</em>' containment reference.
   * @see #setDeclaration(ElementDeclaration)
   * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getItemElement_Declaration()
   * @model containment="true"
   * @generated
   */
  ElementDeclaration getDeclaration();

  /**
   * Sets the value of the '{@link org.xtext.blogPostDSL.ItemElement#getDeclaration <em>Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration</em>' containment reference.
   * @see #getDeclaration()
   * @generated
   */
  void setDeclaration(ElementDeclaration value);

} // ItemElement
