/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Title ID</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.blogPostDSL.TitleID#getTitleid <em>Titleid</em>}</li>
 * </ul>
 *
 * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getTitleID()
 * @model
 * @generated
 */
public interface TitleID extends EObject
{
  /**
	 * Returns the value of the '<em><b>Titleid</b></em>' attribute list.
	 * The list contents are of type {@link java.lang.String}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Titleid</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Titleid</em>' attribute list.
	 * @see org.xtext.blogPostDSL.BlogPostDSLPackage#getTitleID_Titleid()
	 * @model unique="false"
	 * @generated
	 */
  EList<String> getTitleid();

} // TitleID
