/**
 * generated by Xtext 2.10.0
 */
package org.xtext;

import org.xtext.AbstractBlogPostDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class BlogPostDSLRuntimeModule extends AbstractBlogPostDSLRuntimeModule {
}
