/**
 * generated by Xtext 2.10.0
 */
package org.xtext;

import org.xtext.BlogPostDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BlogPostDSLStandaloneSetup extends BlogPostDSLStandaloneSetupGenerated {
  public static void doSetup() {
    BlogPostDSLStandaloneSetup _blogPostDSLStandaloneSetup = new BlogPostDSLStandaloneSetup();
    _blogPostDSLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
