/**
 * generated by Xtext 2.10.0
 */
package org.xtext.generator;

import com.google.inject.Inject;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.xbase.lib.Extension;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class BlogPostDSLGenerator extends AbstractGenerator {
  @Inject
  @Extension
  private IQualifiedNameProvider _iQualifiedNameProvider;
  
  private Date now;
  
  private SimpleDateFormat dateFormatter;
  
  public String getShortDate() {
    Date _date = new Date();
    this.now = _date;
    SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
    this.dateFormatter = _simpleDateFormat;
    return this.dateFormatter.format(this.now);
  }
  
  public String getLongDate() {
    Date _date = new Date();
    this.now = _date;
    SimpleDateFormat _simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss-04:00");
    this.dateFormatter = _simpleDateFormat;
    return this.dateFormatter.format(this.now);
  }
  
  public CharSequence compile(final /* ItemElement */Object ie) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field Tags is undefined"
      + "\nThe method or field getDate is undefined"
      + "\neContainer cannot be resolved"
      + "\nfullyQualifiedName cannot be resolved"
      + "\n!= cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\nfullyQualifiedName cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nTitle cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\nfullyQualifiedName cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nTitle cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\nfullyQualifiedName cannot be resolved"
      + "\n!= cannot be resolved"
      + "\nDate cannot be resolved"
      + "\neContainer cannot be resolved"
      + "\nfullyQualifiedName cannot be resolved"
      + "\n== cannot be resolved");
  }
  
  public void afterGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
  }
  
  public void beforeGenerate(final Resource input, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
  }
  
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ItemElement is undefined"
      + "\nThe method compile(ItemElement) from the type BlogPostDSLGenerator refers to the missing type ItemElement");
  }
}
