/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.blogPostDSL.Article;
import org.xtext.blogPostDSL.BlogPostDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Article</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ArticleImpl extends ItemElementImpl implements Article
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ArticleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlogPostDSLPackage.Literals.ARTICLE;
  }

} //ArticleImpl
