/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.blogPostDSL.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class BlogPostDSLFactoryImpl extends EFactoryImpl implements BlogPostDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static BlogPostDSLFactory init()
  {
    try
    {
      BlogPostDSLFactory theBlogPostDSLFactory = (BlogPostDSLFactory)EPackage.Registry.INSTANCE.getEFactory(BlogPostDSLPackage.eNS_URI);
      if (theBlogPostDSLFactory != null)
      {
        return theBlogPostDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new BlogPostDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BlogPostDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case BlogPostDSLPackage.DOMAINMODEL: return createDomainmodel();
      case BlogPostDSLPackage.ITEM_ELEMENT: return createItemElement();
      case BlogPostDSLPackage.BLOG: return createBlog();
      case BlogPostDSLPackage.ARTICLE: return createArticle();
      case BlogPostDSLPackage.ELEMENT_DECLARATION: return createElementDeclaration();
      case BlogPostDSLPackage.TAG_IMPORT: return createTagImport();
      case BlogPostDSLPackage.TAG: return createTag();
      case BlogPostDSLPackage.TITLE: return createTitle();
      case BlogPostDSLPackage.DATE: return createDate();
      case BlogPostDSLPackage.TAGS: return createTags();
      case BlogPostDSLPackage.TITLE_ID: return createTitleID();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Domainmodel createDomainmodel()
  {
    DomainmodelImpl domainmodel = new DomainmodelImpl();
    return domainmodel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ItemElement createItemElement()
  {
    ItemElementImpl itemElement = new ItemElementImpl();
    return itemElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Blog createBlog()
  {
    BlogImpl blog = new BlogImpl();
    return blog;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Article createArticle()
  {
    ArticleImpl article = new ArticleImpl();
    return article;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ElementDeclaration createElementDeclaration()
  {
    ElementDeclarationImpl elementDeclaration = new ElementDeclarationImpl();
    return elementDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TagImport createTagImport()
  {
    TagImportImpl tagImport = new TagImportImpl();
    return tagImport;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Tag createTag()
  {
    TagImpl tag = new TagImpl();
    return tag;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Title createTitle()
  {
    TitleImpl title = new TitleImpl();
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Date createDate()
  {
    DateImpl date = new DateImpl();
    return date;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Tags createTags()
  {
    TagsImpl tags = new TagsImpl();
    return tags;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TitleID createTitleID()
  {
    TitleIDImpl titleID = new TitleIDImpl();
    return titleID;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public BlogPostDSLPackage getBlogPostDSLPackage()
  {
    return (BlogPostDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static BlogPostDSLPackage getPackage()
  {
    return BlogPostDSLPackage.eINSTANCE;
  }

} //BlogPostDSLFactoryImpl
