/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.blogPostDSL.Blog;
import org.xtext.blogPostDSL.BlogPostDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Blog</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BlogImpl extends ItemElementImpl implements Blog
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected BlogImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return BlogPostDSLPackage.Literals.BLOG;
	}

} //BlogImpl
