/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.blogPostDSL.BlogPostDSLPackage;
import org.xtext.blogPostDSL.ElementDeclaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Element Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ElementDeclarationImpl extends MinimalEObjectImpl.Container implements ElementDeclaration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ElementDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BlogPostDSLPackage.Literals.ELEMENT_DECLARATION;
  }

} //ElementDeclarationImpl
