/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.blogPostDSL.BlogPostDSLPackage;
import org.xtext.blogPostDSL.TagImport;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tag Import</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TagImportImpl extends MinimalEObjectImpl.Container implements TagImport
{
  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected TagImportImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return BlogPostDSLPackage.Literals.TAG_IMPORT;
	}

} //TagImportImpl
