/**
 * generated by Xtext 2.10.0
 */
package org.xtext.blogPostDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.blogPostDSL.BlogPostDSLPackage;
import org.xtext.blogPostDSL.TitleID;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Title ID</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.blogPostDSL.impl.TitleIDImpl#getTitleid <em>Titleid</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TitleIDImpl extends MinimalEObjectImpl.Container implements TitleID
{
  /**
	 * The cached value of the '{@link #getTitleid() <em>Titleid</em>}' attribute list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getTitleid()
	 * @generated
	 * @ordered
	 */
  protected EList<String> titleid;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected TitleIDImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return BlogPostDSLPackage.Literals.TITLE_ID;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public EList<String> getTitleid()
  {
		if (titleid == null) {
			titleid = new EDataTypeEList<String>(String.class, this, BlogPostDSLPackage.TITLE_ID__TITLEID);
		}
		return titleid;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case BlogPostDSLPackage.TITLE_ID__TITLEID:
				return getTitleid();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case BlogPostDSLPackage.TITLE_ID__TITLEID:
				getTitleid().clear();
				getTitleid().addAll((Collection<? extends String>)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case BlogPostDSLPackage.TITLE_ID__TITLEID:
				getTitleid().clear();
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case BlogPostDSLPackage.TITLE_ID__TITLEID:
				return titleid != null && !titleid.isEmpty();
		}
		return super.eIsSet(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public String toString()
  {
		if (eIsProxy()) return super.toString();

		StringBuffer result = new StringBuffer(super.toString());
		result.append(" (titleid: ");
		result.append(titleid);
		result.append(')');
		return result.toString();
	}

} //TitleIDImpl
